### ISSUE TITLE
Priority does not seem to work.

### ISSUE THREAD

**Issue by bwims** [foxleigh81/node-red-contrib-todoist-api#20]
I just added a task to todoist using the following JSON 

```
{
	"content": "test four",
	"project_id": "2262401316",
	"priority": 1
}

```
However, when inspected, the item was added priority 4.

Please advise.

**Comment by bwims** [comment]
Solved it.. Just as well, since nobody seems to be looking at this anymore!

The priorities are INVERTED.  1=4, 2=3, 3=2, 4=1.  

?!??!!

At least I can make it work now!

**Comment by foxleigh81** [comment]
Yeah. Todoist is weird. Sorry for the delay in responding.
