### ISSUE TITLE
Create task node has no dropdown box to select toekn

### ISSUE THREAD

**Issue by silversmarty** [foxleigh81/node-red-contrib-todoist-api#7]
![image](https://user-images.githubusercontent.com/17980711/191995086-77d21111-fdcb-4b59-b268-50833a96532d.png)

And it makes this node useless, because no token can be used (even if it has been configured through a Configuration Node)

Would it be possible to update this node and add a select dropdown like other nodes ? 
Thanks a lot !

**Comment by silversmarty** [comment]
Hi there, have you got any feedback on this bug ? It's very annoying...

Thank you so much !

**Comment by silversmarty** [comment]
Hi there,

well, I've very annoyed but I seems I have no other choice than uninstalling this plugin, as there is no possibility to use TodoIst correctly.
Too bad

**Comment by foxleigh81** [comment]
Sorry, this project has been on my backburner for months and I've been crap at keeping on top of responding to issues. v1.0.0 was released a few months ago which fixes this bug. I'll try to keep on top of it going forward as I have some help now.
